### ISSUE TITLE
DDNA 4.2.1+ iOSNotifications.cs backwards compatibility with Unity 4.7 missing

### ISSUE THREAD

**Issue by msifnioti** [deltaDNA/unity-sdk#2]
At two places in _iOSNotifications.cs_ , the following line needs to be:
`            #if UNITY_4_5 || UNITY_4_6            
`
-->
`            #if UNITY_4_5 || UNITY_4_6 || UNITY_4_7             
`

**Comment by dwxw** [comment]
Good spot.  We've added that into the latest patch.  Thank you.
